/**
 * pagesListActions.ts -  An enum with all the types of actions to use in our reducer
 */

export enum pageActions {
    ACTIVATE_FIRST = "ACTIVATE_FIRST",
    DEACTIVATE_FIRST = "DEACTIVATE_FIRST",
    ACTIVATE_PREV = "ACTIVATE_PREV",
    DEACTIVATE_PREV = "DEACTIVATE_PREV",
    ACTIVATE_ELLIPSE_LEFT = "ACTIVATE_ELLIPSE_LEFT",
    DEACTIVATE_ELLIPSE_LEFT = "DEACTIVATE_ELLIPSE_LEFT",
    ACTIVATE_LAST = "ACTIVATE_LAST",
    DEACTIVATE_LAST = "DEACTIVATE_LAST",
    ACTIVATE_NEXT = "ACTIVATE_NEXT",
    DEACTIVATE_NEXT = "DEACTIVATE_NEXT",
    ACTIVATE_ELLIPSE_RIGTH = "ACTIVATE_ELLIPSE_RIGTH",
    DEACTIVATE_ELLIPSE_RIGTH = "DEACTIVATE_ELLIPSE_RIGTH",
    UPDATE_PAGE_VIEWER = "UPDATE_PAGE_VIEWER"
  }
